prompts=(🍏 🍎 🍐 🍊 🍋 🍌 🍉 🍇 🍓 🫐 🍈 🍒 🥭 🍍 🥥 🥝 🍅 🍆 🥑 🥦 🥬 🥒 🫑 🌽 🥕 🫒 🧄)
size=${#prompts[@]}
index=$(($RANDOM % $size))
prompt=${prompts[$index]}
PROMPT_COMMAND='echo -ne "\033]0;$(whoami)@$(hostname):$(pwd) ${prompt}\007"'
PS1="${prompt} "
export TERM=xterm-color
export COLORTERM=truecolor

fuzzy_history() {
    history | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}' | fzf
}
