map <Space> <Leader>

map U :redo<Return>
map <Leader>bb :buffers<Return>

map <Leader>fs :w<Return>
map <Leader>ff :e<Space>

map <Leader>qq :quitall<Return>

map <Leader>w- :split<Return>
map <Leader>w/ :vsplit<Return>
map <Leader>wd :wq<Return>
map <Leader>wj <c-w>j
map <Leader>wk <c-w>k
map <Leader>wh <c-w>h
map <Leader>wl <c-w>l
map <Leader>wm :only<Return>

map <Leader>jl :<Space>

map <Leader>! :!<Space>

